# Generated by Django 3.2.24 on 2024-07-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='observed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
