# Generated by Django 3.2.24 on 2024-07-23 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0002_question_observed_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('license_code', models.CharField(max_length=50)),
                ('attribution', models.CharField(max_length=200)),
                ('times_shown', models.IntegerField(default=0)),
                ('times_incorrect', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inaturalist_id', models.IntegerField(unique=True)),
                ('observed_on', models.DateField()),
                ('url', models.URLField()),
                ('times_shown', models.IntegerField(default=0)),
                ('times_incorrect', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserIncorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.image')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.observation')),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quizsession')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='times_incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='times_shown',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
        migrations.AddField(
            model_name='userincorrectanswer',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.species'),
        ),
        migrations.AddField(
            model_name='userincorrectanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observation',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.species'),
        ),
        migrations.AddField(
            model_name='image',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.observation'),
        ),
    ]
