# Generated by Django 3.2.24 on 2024-07-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_achievement_userachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.image')),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quizsession')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.species')),
                ('user_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answers', to='quiz_app.species')),
            ],
            options={
                'unique_together': {('quiz_session', 'question_number')},
            },
        ),
    ]
