# Generated by Django 3.2.24 on 2024-07-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_quizquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(blank=True, default='achievements/default_achievement.png', null=True, upload_to='achievements/'),
        ),
    ]
