# Generated by Django 3.2.24 on 2024-07-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_alter_achievement_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='icon',
        ),
    ]
