# Generated by Django 3.2.24 on 2024-07-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_remove_achievement_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/'),
        ),
    ]
