# Generated by Django 5.0.7 on 2024-07-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_achievement_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(upload_to='quiz_images/'),
        ),
    ]
