# Generated by Django 5.0.7 on 2024-07-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0012_userprofile_avatar_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='species_observation_history',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
