# Generated by Django 5.0.7 on 2024-07-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0013_userprofile_species_observation_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='total_questions',
            field=models.IntegerField(default=10),
        ),
    ]
