# Generated by Django 5.0.7 on 2024-07-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0014_alter_quizsession_total_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='species_observation_history',
            field=models.JSONField(default=dict),
        ),
    ]
