# Generated by Django 5.0.7 on 2024-07-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0016_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='quiz_type',
            field=models.CharField(choices=[('multiple_choice', 'Scelta Multipla'), ('text_input', 'Inserimento Testo')], default={}, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
