# Generated by Django 5.0.7 on 2024-07-31 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0017_quizsession_quiz_type_alter_quizsession_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='user_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_session_answers', to='quiz_app.species'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='user_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_question_answers', to='quiz_app.species'),
        ),
    ]
