# Generated by Django 5.0.7 on 2024-08-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0018_quizsession_user_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='difficult_species',
            field=models.JSONField(default=dict),
        ),
    ]
