# Generated by Django 5.0.7 on 2024-08-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0019_userprofile_difficult_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='condition',
            field=models.CharField(default={}, max_length=255),
            preserve_default=False,
        ),
    ]
