# Generated by Django 5.0.7 on 2024-09-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0023_alter_quizquestion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
    ]
