# Generated by Django 4.2.2 on 2024-10-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0027_userprofile_confirmation_token'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz_session', 'image'], name='quiz_app_qu_quiz_se_6b9a37_idx'),
        ),
    ]
