# Generated by Django 4.2.2 on 2024-10-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0028_quizquestion_quiz_app_qu_quiz_se_6b9a37_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
